return {
    -- {
    --     'yetone/avante.nvim',
    --     event = 'VeryLazy',
    --     version = false,
    --     opts = {
    --         provider = 'gemini',
    --         auto_suggestions_provider = 'gemini',
    --         gemini = {
    --             endpoint = 'https://generativelanguage.googleapis.com/v1beta/models',
    --             model = 'gemini-2.5-pro-exp-03-25',
    --             timeout = 30000,
    --             temperature = 0,
    --             max_tokens = 8192 * 4,
    --             -- reasoning_effort = 'medium',
    --         },
    --     },
    --     build = 'make BUILD_FROM_SOURCE=true',
    --     dependencies = {
    --         'MunifTanjim/nui.nvim',
    --         'nvim-lua/plenary.nvim',
    --         'stevearc/dressing.nvim',
    --         'nvim-tree/nvim-web-devicons',
    --         'nvim-telescope/telescope.nvim',
    --         'nvim-treesitter/nvim-treesitter',
    --         {
    --             'HakonHarnes/img-clip.nvim',
    --             event = 'VeryLazy',
    --             opts = {
    --                 default = {
    --                     embed_image_as_base64 = false,
    --                     prompt_for_file_name = false,
    --                     drag_and_drop = { insert_mode = true },
    --                     -- required for Windows users
    --                     use_absolute_path = true,
    --                 },
    --             },
    --         },
    --         {
    --             'MeanderingProgrammer/render-markdown.nvim',
    --             opts = { file_types = { 'Avante' } },
    --             ft = { 'Avante' },
    --         },
    --     },
    -- },
    --
    -- {
    --     'saghen/blink.cmp',
    --     dependencies = {
    --         'Kaiser-Yang/blink-cmp-avante',
    --     },
    --     opts = {
    --         sources = {
    --             -- Add 'avante' to the list
    --             default = { 'avante' },
    --             providers = {
    --                 avante = {
    --                     module = 'blink-cmp-avante',
    --                     name = 'Avante',
    --                     opts = {},
    --                 },
    --             },
    --         },
    --     },
    -- },
}
